apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
    editable: true

  - name: eventsproc-metrics
    type: prometheus
    access: proxy
    url: http://eventsproc:2113
    editable: true
    jsonData:
      httpMethod: GET
      prometheusType: Prometheus
